### ISSUE TITLE
testing commiteth6

### ISSUE THREAD

**Issue by tpatja** [tpatja/trrnt#6]

**Comment by test-2016-07-06** [comment]
Current balance: 0.0000 ETH
![QR Code](http://91.145.77.247:3000/qr/tpatja/trrnt/bounty/6/3055340884a2ec17c673948dfe26b7ff1ccc482a9d419f15097202e6c4097bcb/qr.png)
[http://91.145.77.247:3000](http://91.145.77.247:3000)
